tasks:
  - name: Package
    init: yarn install && yarn link
    command: yarn watch

  - name: Web App
    init: cd example && yarn link react-slid
    command: cd example && yarn start

ports:
  - name: Web App
    port: 3000
    visibility: private
    onOpen: notify